micronaut:
  application:
    name: seed-desafio-cdc
datasources:
  default:
    name: cdcDB
    url:  jdbc:mysql://localhost:3308/cdcDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
